import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import ReduxStoreProvider from "./ReduxStoreProvider";
import ReactToastifyProvider from "./ReactToastifyProvider";
import GlobalLoading from "./GlobalLoading";
import MainContent from './MainContent';
import {Navbar} from './_components';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Flash Card",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode
}

const RootLayout: React.FunctionComponent<RootLayoutProps> = ({children}) => {
	return (
		<html lang="en">
      		<body className={inter.className}>
				<ReduxStoreProvider>
					<ReactToastifyProvider>
						<GlobalLoading>
							<MainContent>
								<Navbar/>
								<section className="p-4 bg-amber-100">
									{children}
								</section>
							</MainContent>
						</GlobalLoading>
					</ReactToastifyProvider>
				</ReduxStoreProvider>
			</body>
    	</html>
	);
}

export default RootLayout;